<?php
/**
 *Defines Configuration-Array depending on application-context.
 *Further configs can be found in ({@link ../Configuration/LocalConfiguration.php}) and ({@link ../Configuration/AdditionalConfiguration.php})
 *
 * NEXT STEPS: Consolidate configuration in other files.
 *
 */
/**
 * You can control policies via Cryptshare Administrator Interface on:
 * https://cryptshare-test4.equinoxe.de:8080/ai/Login?1
 * Just log in, click on "System Settings" -> "Policy Settings" and search for the email address
 */
// Keys
const TYPO3_CONTEXT = 'TYPO3_CONTEXT';
const ENVIRONMENT = 'environment';
const CLIENT_ID = 'client_id';
const CLIENT_SECRET = 'client_secret';
const PLAN_ID = 'plan_id';
const CRYPTSHARE_HOST = 'cryptshare_host';
const CRYPTSHARE_HOST_PURE = 'cryptshare_host_pure';
const CRYPTSHARE_USER = 'cryptshare_user';
const CRYPTSHARE_PASSWD = 'cryptshare_password';
const FORCE_CC_RECIPIENT_ADDRESS = 'forceCCRecipientAddress';
const FORCE_CC_RECIPIENT_ADDRESS_2 = 'forceCCRecipientAddress2';
const FORCE_CC_RECIPIENT_ADDRESS_3 = 'forceCCRecipientAddress3';
const MAIL_TO = 'MAILTo';
const DELETE_CVS = 'deleteCSVs';
const SMTP_DEBUG = 'SMTPDebug';
const DEV_IP = 'DevIP';
const SMTP_PORT = 'SMTPPort';
const SMTP_HOST = 'SMTPHost';
const SMTP_USERNAME = 'SMTPUsername';
const SMTP_PASSWD = 'SMTPPassword';
const MAIL_FORM = 'MAILFrom';
const SMTP_SECURE = 'SMTPSecure';
const NEW_CRYPTSHARE_PASSWD = 'new_cryptshare_password';
const NEW_CRYPTSHARE_USER = 'new_cryptshare_user';
const TYPO3_DB_HOST= 'typo3_dbhost';
const TYPO3_DB_NAME = 'typo3_dbname';
const TYPO3_DB_USER = 'typo3_dbuser';
const TYPO3_DB_PASSWD = 'typo3_dbpassword';
const TYPO3_ENCRYPTIONKEY = 'typo3_encryptionkey';
const IPDB_DB_HOST = 'ipdb_dbhost';
const IPDB_DB_NAME = 'ipdb_dbname';
const IPDB_DB_USER = 'ipdb_dbuser';
const IPDB_DB_PASSWD = 'ipdb_dbpassword';
const LOGPATH = 'log_path';

/** Global values */
const SANDBOX = 'sandbox';
const APP = 'app';

/** Local values */
const CS_BETA_SERVER = 'https://cryptshare-test4.equinoxe.de/';
const BW_CLIENT_ID_LOCAL_VALUE = '5dfccbe59cc9ba0df4bc8770';
const BW_CLIENT_SECRET_LOCAL_VALUE = 'b45428cfe6d5b69ab3ed7ace4f8bcd53';
const BW_PLAN_ID_LOCAL_VALUE = '5b56dbec81b1f012b0effc4a';
const CS_CRYPTSHARE_HOST_BETA_LOCAL_VALUE = 'https://cryptshare-test4.equinoxe.de/service/ai?wsdl';
const CS_CRYPTSHARE_HOST_PURE_BETA_LOCAL_VALUE = CS_BETA_SERVER;
const CS_USER_LOCAL_VALUE = 'wsdl.api';
const CS_PASSWD_LOCAL_VALUE = '6fi?PIY~l76Z#oqM';
const CS_CC_RECIPIENT_ADDRESS_LOCAL_VALUE = 'cs-express@equinoxe.com';
const CS_CC_RECIPIENT_ADDRESS_2_LOCAL_VALUE = '';
const CS_CC_RECIPIENT_ADDRESS_3_LOCAL_VALUE = '';
const MAIL_TO_LOCAL_VALUE = 'info@dev.cryptshare.express';
const DEV_IP_LOCAL_VALUE = '87.190.45.234';
const CS_SERVER_NL_LOCAL_VALUE = 'https://nl.cryptshare.express/';
const CS_SERVER_BETA_LOCAL_VALUE = CS_BETA_SERVER;
const CS_SERVER_WEBAPP_LOCAL_VALUE = 'https://webapp.cryptshare.express/';
const SMTP_PORT_LOCAL_VALUE = '1025';
const SMTP_HOST_LOCAL_VALUE = 'mailhog-dev';
const SMTP_USERNAME_LOCAL_VALUE = 'wp13303627-expr_info';
const SMTP_PASSWD_LOCAL_VALUE = '_3Xp+9g6x-Py5K';
const TYPO3_DB_HOST_LOCAL_VALUE = 'db';
const TYPO3_DB_NAME_LOCAL_VALUE = 'db';
const TYPO3_DB_USER_LOCAL_VALUE = 'db';
const TYPO3_DB_PASSWD_LOCAL_VALUE = 'db';
const IPDB_DB_NAME_LOCAL_VALUE = 'ipdb';
const TYPO3_ENCRYPTIONKEY_LOCAL_VALUE = '6c1f69c7502b52a252093f8c5252fa3cd1d5334dcef716b6ec2164356f29216ecccb9d152dad8b4ec08a07ddf070571e';
const DB_HOST_LOCAL_VALUE = 'localhost';
const LOGPATH_LOCAL_VALUE = '/is/htdocs/wp13251579_RIVEMTPQCA/www/logging/dev/';
const DELETE_CVS_LOCAL_VALUE = false;
const SMTP_DEBUG_LOCAL_VALUE = 0;

/** Dev values */
const BW_CLIENT_ID_DEV_VALUE = '5dfccbe59cc9ba0df4bc8770';
const BW_CLIENT_SECRET_DEV_VALUE = 'b45428cfe6d5b69ab3ed7ace4f8bcd53';
const BW_PLAN_ID_DEV_VALUE = '5b56dbec81b1f012b0effc4a';
const CS_CRYPTSHARE_HOST_BETA_DEV_VALUE = CS_BETA_SERVER.'service/ai?wsdl';
const CS_USER_DEV_VALUE = 'wsdl.api';
const CS_PASSWD_DEV_VALUE = "UeY5+@M]/'xI0XII<";
const CS_CC_RECIPIENT_ADDRESS_DEV_VALUE = 'cs-express@equinoxe.com';
const CS_CC_RECIPIENT_ADDRESS_2_DEV_VALUE = '';
const CS_CC_RECIPIENT_ADDRESS_3_DEV_VALUE = '';
const MAIL_TO_DEV_VALUE = 'cs-x-dev@equinoxe.de';
const DEV_IP_DEV_VALUE = '80.72.128.34';
const CS_SERVER_NL_DEV_VALUE = 'https://nl.cryptshare.express/';
const CS_SERVER_BETA_DEV_VALUE = CS_BETA_SERVER;
const CS_SERVER_WEBAPP_DEV_VALUE = 'https://webapp.cryptshare.express/';
const SMTP_PORT_DEV_VALUE = '25';
//const SMTP_HOST_DEV_VALUE = 'darkgate.equinoxe.de';
const SMTP_HOST_DEV_VALUE = '192.168.18.116';
const SMTP_USERNAME_DEV_VALUE = 'cs-x-dev@equinoxe.de';
const SMTP_PASSWD_DEV_VALUE = 'zpWB3_9zqp-tGqrq';
const MAIL_FORM_DEV_VALUE = 'cs-x-dev@equinoxe.de';
const SMTP_SECURE_DEV_VALUE = 'tls';
const TYPO3_DB_HOST_DEV_VALUE = 'localhost';
const TYPO3_DB_NAME_DEV_VALUE = 'db13303627-xpr10';
const TYPO3_DB_USER_DEV_VALUE = 'db13303627-xpr10';
const TYPO3_DB_PASSWD_DEV_VALUE = 'GJe_3_he6Z42jvC';
const IPDB_DB_NAME_DEV_VALUE = 'db13303627-ipdb';
const IPDB_DB_USER_DEV_VALUE = 'db13303627-ipdb';
const IPDB_DB_PASSWD_DEV_VALUE = '_N3w+1pdb7';
const TYPO3_ENCRYPTIONKEY_DEV_VALUE = '72430f0c162ec54c59386e886d69789883f05e161f6cde727b69d373c040f624c1a0ba3779c3429e3fbfc602d42510b9';
const DB_HOST_DEV_VALUE = 'localhost';
const LOGPATH_DEV_VALUE = '/srv/www/virtual/cs-x-dev.equinoxe.de/www/logging/dev/';
const DELETE_CVS_DEV_VALUE = false;
const SMTP_DEBUG_DEV_VALUE = 0;

/** Live values */
const BW_CLIENT_ID_LIVE_VALUE = '5dfccbf14802012700bf47de';
const BW_CLIENT_SECRET_LIVE_VALUE = 'bc8fb9f670b4ba968e01a271631d9c4a';
const BW_PLAN_ID_LIVE_VALUE = '5bbf3551e369ee0ddcb47dc8';
const CS_CRYPTSHARE_HOST_BETA_LIVE_VALUE = CS_BETA_SERVER.'service/ai?wsdl';
const CS_CRYPTSHARE_HOST_WEBAPP_LIVE_VALUE = 'https://webapp.cryptshare.express/service/ai?wsdl';
const CS_CRYPTSHARE_HOST_PURE_WEBAPP_LIVE_VALUE = 'https://webapp.cryptshare.express/';
const CS_USER_LIVE_VALUE = 'wsdl.api';
const CS_PASSWD_LIVE_VALUE = 'VKM02_NAp01-Urt5oublbF';
const CS_CC_RECIPIENT_ADDRESS_LIVE_VALUE = 'cs-express@equinoxe.com';
const CS_CC_RECIPIENT_ADDRESS_2_LIVE_VALUE = '';
const CS_CC_RECIPIENT_ADDRESS_3_LIVE_VALUE = '';
const MAIL_TO_LIVE_VALUE = 'info@dev.cryptshare.express';
const DEV_IP_LIVE_VALUE = '87.190.45.234';
const CS_SERVER_NL_LIVE_VALUE = 'https://nl.cryptshare.express/';
const CS_SERVER_BETA_LIVE_VALUE = CS_BETA_SERVER;
const CS_SERVER_WEBAPP_LIVE_VALUE = 'https://webapp.cryptshare.express/';
const MAIL_FORM_LIVE_VALUE = 'support@cryptshare.express';
const SMTP_PORT_LIVE_VALUE = '25';
const SMTP_HOST_LIVE_VALUE = 'darkgate.equinoxe.de';
const SMTP_PASSWD_LIVE_VALUE = 'UPknP-W9q4_RiwKFE47AT';
const SMTP_SECURE_LIVE_VALUE = 'tls';
const SMTP_USERNAME_LIVE_VALUE = 'support@cryptshare.express';
const IPDB_DB_NAME_LIVE_VALUE = 'db13251579-ipdb';
const IPDB_DB_USER_LIVE_VALUE = 'db13251579-ipdb';
const IPDB_DB_PASSWD_LIVE_VALUE = '_N3w+1pdb7';
const TYPO3_DB_NAME_LIVE_VALUE = 'db13251579-t311l';
const TYPO3_DB_USER_LIVE_VALUE = 'db13251579-t311l';
const TYPO3_DB_PASSWD_LIVE_VALUE = 'P4j_3JNT2-HX49oi';
const FORCE_CC_RECIPIENT_ADDRESS_LIVE_VALUE = '';
const TYPO3_ENCRYPTIONKEY_LIVE_VALUE = '72430f0c162ec54c59386e886d69789883f05e161f6cde727b69d373c040f624c1a0ba3779c3429e3fbfc602d42510b9';
const DB_HOST_LIVE_VALUE = 'localhost';
const LOGPATH_LIVE_VALUE = '/srv/www/virtual/cs-x-www.equinoxe.de/www/logging/dev/';
const DELETE_CVS_LIVE_VALUE = false;
const SMTP_DEBUG_LIVE_VALUE = 0;

if($_SERVER[TYPO3_CONTEXT] == 'Development/Local'){
    $config['db_kpi_host'] = 'localhost';
    $config['db_kpi_user'] = 'db13251579-bwsta';
    $config['db_kpi_pwd'] = 'ug7A9QpRoopd_VX';
    $config['db_kpi_name'] = 'db13251579-bwsta';
    $config[LOGPATH] = LOGPATH_LOCAL_VALUE;
    $config[ENVIRONMENT] = SANDBOX;
    $config[CLIENT_ID] = BW_CLIENT_ID_LOCAL_VALUE;
    $config[CLIENT_SECRET] = BW_CLIENT_SECRET_LOCAL_VALUE;
    $config[PLAN_ID] = BW_PLAN_ID_LOCAL_VALUE;
    $config[CRYPTSHARE_HOST] = CS_CRYPTSHARE_HOST_BETA_LOCAL_VALUE;
    $config[CRYPTSHARE_HOST_PURE] = CS_CRYPTSHARE_HOST_PURE_BETA_LOCAL_VALUE;
    $config[CRYPTSHARE_USER] = CS_USER_LOCAL_VALUE;
    $config[CRYPTSHARE_PASSWD] = CS_PASSWD_LOCAL_VALUE;
    $config[FORCE_CC_RECIPIENT_ADDRESS] = CS_CC_RECIPIENT_ADDRESS_LOCAL_VALUE;
    $config[FORCE_CC_RECIPIENT_ADDRESS_2] = CS_CC_RECIPIENT_ADDRESS_2_LOCAL_VALUE;
    $config[FORCE_CC_RECIPIENT_ADDRESS_3] = CS_CC_RECIPIENT_ADDRESS_3_LOCAL_VALUE;
    $config[MAIL_TO] = MAIL_TO_LOCAL_VALUE;
    $config[DELETE_CVS] = DELETE_CVS_LOCAL_VALUE;
    $config[SMTP_DEBUG] = SMTP_DEBUG_LOCAL_VALUE;
    $config[DEV_IP] = DEV_IP_LOCAL_VALUE;
    $config[SMTP_PORT] = SMTP_PORT_LOCAL_VALUE;
    $config[SMTP_HOST] = SMTP_HOST_LOCAL_VALUE;
    $config[SMTP_USERNAME] = SMTP_USERNAME_LOCAL_VALUE;
    $config[SMTP_PASSWD] = SMTP_PASSWD_LOCAL_VALUE;
    $config[MAIL_FORM] = MAIL_TO_LOCAL_VALUE;
    $config[SMTP_SECURE] = '';
    $config[NEW_CRYPTSHARE_PASSWD] = [
        CS_SERVER_NL_LOCAL_VALUE => CS_PASSWD_LOCAL_VALUE,
        CS_SERVER_BETA_LOCAL_VALUE => CS_PASSWD_LOCAL_VALUE
    ];
    $config[NEW_CRYPTSHARE_USER] = [
        CS_SERVER_NL_LOCAL_VALUE => CS_USER_LOCAL_VALUE,
        CS_SERVER_BETA_LOCAL_VALUE => CS_USER_LOCAL_VALUE
    ];
    $config[TYPO3_DB_HOST] = TYPO3_DB_HOST_LOCAL_VALUE;
    $config[TYPO3_DB_NAME] = TYPO3_DB_NAME_LOCAL_VALUE;
    $config[TYPO3_DB_USER] = TYPO3_DB_USER_LOCAL_VALUE;
    $config[TYPO3_DB_PASSWD] = TYPO3_DB_PASSWD_LOCAL_VALUE;
    $config[TYPO3_ENCRYPTIONKEY] = TYPO3_ENCRYPTIONKEY_LOCAL_VALUE;
    $config[IPDB_DB_HOST] = TYPO3_DB_HOST_LOCAL_VALUE;
    $config[IPDB_DB_NAME] = IPDB_DB_NAME_LOCAL_VALUE;
    $config[IPDB_DB_USER] = TYPO3_DB_USER_LOCAL_VALUE;
    $config[IPDB_DB_PASSWD] = TYPO3_DB_PASSWD_LOCAL_VALUE;
} elseif($_SERVER[TYPO3_CONTEXT] == 'Development' || $_SERVER[TYPO3_CONTEXT] == 'Development/V10'){
    $config['db_kpi_host'] = 'localhost';
    $config['db_kpi_user'] = 'db13303627-bwsta';
    $config['db_kpi_pwd'] = 'ug7A9QpRoopd_VX';
    $config['db_kpi_name'] = 'db13303627-bwsta';
    $config[LOGPATH] = LOGPATH_DEV_VALUE;
    $config[ENVIRONMENT] = SANDBOX;
    $config[CLIENT_ID] = BW_CLIENT_ID_DEV_VALUE;
    $config[CLIENT_SECRET] = BW_CLIENT_SECRET_DEV_VALUE;
    $config[PLAN_ID] = BW_PLAN_ID_DEV_VALUE;
    $config[CRYPTSHARE_HOST] = CS_CRYPTSHARE_HOST_BETA_DEV_VALUE;
    $config[CRYPTSHARE_HOST_PURE] = CS_CRYPTSHARE_HOST_PURE_BETA_LOCAL_VALUE;
    $config[CRYPTSHARE_USER] = CS_USER_DEV_VALUE;
    $config[CRYPTSHARE_PASSWD] = CS_PASSWD_DEV_VALUE;
    $config[FORCE_CC_RECIPIENT_ADDRESS] = CS_CC_RECIPIENT_ADDRESS_DEV_VALUE;
    $config[FORCE_CC_RECIPIENT_ADDRESS_2] = CS_CC_RECIPIENT_ADDRESS_2_DEV_VALUE;
    $config[FORCE_CC_RECIPIENT_ADDRESS_3] = CS_CC_RECIPIENT_ADDRESS_3_DEV_VALUE;
    $config[MAIL_TO] = MAIL_TO_DEV_VALUE;
    $config[DELETE_CVS] = DELETE_CVS_DEV_VALUE;
    $config[SMTP_DEBUG] = SMTP_DEBUG_DEV_VALUE;
    $config[DEV_IP] = DEV_IP_DEV_VALUE;
    $config[SMTP_PORT] = SMTP_PORT_DEV_VALUE;
    $config[SMTP_HOST] = SMTP_HOST_DEV_VALUE;
    $config[SMTP_USERNAME] = SMTP_USERNAME_DEV_VALUE;
    $config[SMTP_PASSWD] = SMTP_PASSWD_DEV_VALUE;
    $config[MAIL_FORM] = MAIL_FORM_DEV_VALUE;
    $config[SMTP_SECURE] = SMTP_SECURE_DEV_VALUE;
    $config[NEW_CRYPTSHARE_PASSWD] = [
        CS_SERVER_NL_DEV_VALUE => CS_PASSWD_DEV_VALUE,
        CS_SERVER_BETA_DEV_VALUE => CS_PASSWD_DEV_VALUE
    ];
    $config[NEW_CRYPTSHARE_USER] = [
        CS_SERVER_NL_DEV_VALUE => CS_USER_DEV_VALUE,
        CS_SERVER_BETA_DEV_VALUE => CS_USER_DEV_VALUE
    ];
    $config[TYPO3_DB_HOST] = DB_HOST_DEV_VALUE;
    $config[TYPO3_DB_NAME] = TYPO3_DB_NAME_DEV_VALUE;
    $config[TYPO3_DB_USER] = TYPO3_DB_USER_DEV_VALUE;
    $config[TYPO3_DB_PASSWD] = TYPO3_DB_PASSWD_DEV_VALUE;
    $config[TYPO3_ENCRYPTIONKEY] = TYPO3_ENCRYPTIONKEY_DEV_VALUE;
    $config[IPDB_DB_HOST] = DB_HOST_DEV_VALUE;
    $config[IPDB_DB_NAME] = IPDB_DB_NAME_DEV_VALUE;
    $config[IPDB_DB_USER] = IPDB_DB_USER_DEV_VALUE;
    $config[IPDB_DB_PASSWD] = IPDB_DB_PASSWD_DEV_VALUE;
} else {
    $config['db_kpi_host'] = 'localhost';
    $config['db_kpi_user'] = 'db13251579-bwsta';
    $config['db_kpi_pwd'] = 'om5PGOdK';
    $config['db_kpi_name'] = 'db13251579-bwsta';
    $config[LOGPATH] = LOGPATH_LIVE_VALUE;
    $config[ENVIRONMENT] = APP;
    $config[CLIENT_ID] = BW_CLIENT_ID_LIVE_VALUE;
    $config[CLIENT_SECRET] = BW_CLIENT_SECRET_LIVE_VALUE;
    $config[PLAN_ID] = BW_PLAN_ID_LIVE_VALUE;
    $config[FORCE_CC_RECIPIENT_ADDRESS] = FORCE_CC_RECIPIENT_ADDRESS_LIVE_VALUE;
    $config[FORCE_CC_RECIPIENT_ADDRESS_2] = CS_CC_RECIPIENT_ADDRESS_2_LIVE_VALUE;
    $config[FORCE_CC_RECIPIENT_ADDRESS_3] = CS_CC_RECIPIENT_ADDRESS_3_LIVE_VALUE;
    $config[MAIL_TO] = MAIL_FORM_LIVE_VALUE;
    $config[DELETE_CVS] = DELETE_CVS_LIVE_VALUE;
    $config[SMTP_DEBUG] = SMTP_DEBUG_LIVE_VALUE;
    $config[DEV_IP] = DEV_IP_LIVE_VALUE;
    $config[SMTP_PORT] = SMTP_PORT_LIVE_VALUE;
    $config[SMTP_HOST] = SMTP_HOST_LIVE_VALUE;
    $config[SMTP_USERNAME] = SMTP_USERNAME_LIVE_VALUE;
    $config[SMTP_PASSWD] = SMTP_PASSWD_LIVE_VALUE;
    $config[MAIL_FORM] = MAIL_FORM_LIVE_VALUE;
    $config[SMTP_SECURE] = SMTP_SECURE_LIVE_VALUE;
    $config[CRYPTSHARE_HOST] = CS_CRYPTSHARE_HOST_WEBAPP_LIVE_VALUE;
    $config[CRYPTSHARE_HOST_PURE] = CS_CRYPTSHARE_HOST_PURE_WEBAPP_LIVE_VALUE;
    $config[CRYPTSHARE_USER] = CS_USER_LIVE_VALUE;
    $config[CRYPTSHARE_PASSWD] = CS_PASSWD_LIVE_VALUE;
    $config[NEW_CRYPTSHARE_PASSWD] = [
        CS_SERVER_NL_LIVE_VALUE => CS_PASSWD_LIVE_VALUE,
        CS_SERVER_WEBAPP_LIVE_VALUE => CS_PASSWD_LIVE_VALUE
    ];
    $config[NEW_CRYPTSHARE_USER] = [
        CS_SERVER_NL_LIVE_VALUE => CS_USER_LIVE_VALUE,
        CS_SERVER_WEBAPP_LIVE_VALUE => CS_USER_LIVE_VALUE
    ];
    $config[TYPO3_DB_HOST] = DB_HOST_LIVE_VALUE;
    $config[TYPO3_DB_NAME] = TYPO3_DB_NAME_LIVE_VALUE;
    $config[TYPO3_DB_USER] = TYPO3_DB_USER_LIVE_VALUE;
    $config[TYPO3_DB_PASSWD] = TYPO3_DB_PASSWD_LIVE_VALUE;
    $config[TYPO3_ENCRYPTIONKEY] = TYPO3_ENCRYPTIONKEY_LIVE_VALUE;
    $config[IPDB_DB_HOST] = DB_HOST_LIVE_VALUE;
    $config[IPDB_DB_NAME] = IPDB_DB_NAME_LIVE_VALUE;
    $config[IPDB_DB_USER] = IPDB_DB_USER_LIVE_VALUE;
    $config[IPDB_DB_PASSWD] = IPDB_DB_PASSWD_LIVE_VALUE;
}
//Should be obsolete in the meantime. Please check if it is used or can be removed
$config['currency'] = 'EUR';
$config['http_status'] = [
    '200' => 'OK: the request was successful.',
    '201' => 'Created: the request was successful, and one or more entities was created.',
    '304' => 'Not Modified: the entity was not updated, possibly because the ETag condition, such as If-Match or If-None-Match, stopped the request from completing.',
    '400' => 'Bad Request: the request was not properly formed and therefore was not successful.',
    '401' => 'Unauthorized',
    '404' => 'Not found',
    '405' => 'Method Not Allowed: the syntax of the request does not match the request type. The Allow header provides more information about the supported types.',
    '406' => 'Not Acceptable: the Accept header response type is not supported. The supported types are XML and JSON.',
    '409' => 'Conflict: the entity or entities cannot be overwritten or deleted.',
    '412' => 'Precondition Failed: when the If-Match header is included in the request, this status indicates that the ETag information did not match and therefore the entity was not updated.',
    '413' => 'Request Too Large: the number of entities that is returned is too large.',
    '415' => 'Unsupported Media Type: the request contains a format that the server cannot interpret.',
    '422' => 'UnprocessableEntity',
    '500' => 'Internal Server Error: this status indicates that an error occurred on the server and it was unable to respond.',
    '503' => 'Service Not Available: the solution is not ready and could not respond to the request.'
];
$config['curl_ErrorNo']=[
    '1' => 'CURLE_UNSUPPORTED_PROTOCOL',
    '2' => 'CURLE_FAILED_INIT',
    '3' => 'CURLE_URL_MALFORMAT',
    '4' => 'CURLE_URL_MALFORMAT_USER',
    '5' => 'CURLE_COULDNT_RESOLVE_PROXY',
    '6' => 'CURLE_COULDNT_RESOLVE_HOST',
    '7' => 'CURLE_COULDNT_CONNECT',
    '8' => 'CURLE_FTP_WEIRD_SERVER_REPLY',
    '9' => 'CURLE_REMOTE_ACCESS_DENIED',
    '11' => 'CURLE_FTP_WEIRD_PASS_REPLY',
    '13' => 'CURLE_FTP_WEIRD_PASV_REPLY',
    '14'=>'CURLE_FTP_WEIRD_227_FORMAT',
    '15' => 'CURLE_FTP_CANT_GET_HOST',
    '17' => 'CURLE_FTP_COULDNT_SET_TYPE',
    '18' => 'CURLE_PARTIAL_FILE',
    '19' => 'CURLE_FTP_COULDNT_RETR_FILE',
    '21' => 'CURLE_QUOTE_ERROR',
    '22' => 'CURLE_HTTP_RETURNED_ERROR',
    '23' => 'CURLE_WRITE_ERROR',
    '25' => 'CURLE_UPLOAD_FAILED',
    '26' => 'CURLE_READ_ERROR',
    '27' => 'CURLE_OUT_OF_MEMORY',
    '28' => 'CURLE_OPERATION_TIMEDOUT',
    '30' => 'CURLE_FTP_PORT_FAILED',
    '31' => 'CURLE_FTP_COULDNT_USE_REST',
    '33' => 'CURLE_RANGE_ERROR',
    '34' => 'CURLE_HTTP_POST_ERROR',
    '35' => 'CURLE_SSL_CONNECT_ERROR',
    '36' => 'CURLE_BAD_DOWNLOAD_RESUME',
    '37' => 'CURLE_FILE_COULDNT_READ_FILE',
    '38' => 'CURLE_LDAP_CANNOT_BIND',
    '39' => 'CURLE_LDAP_SEARCH_FAILED',
    '41' => 'CURLE_FUNCTION_NOT_FOUND',
    '42' => 'CURLE_ABORTED_BY_CALLBACK',
    '43' => 'CURLE_BAD_FUNCTION_ARGUMENT',
    '45' => 'CURLE_INTERFACE_FAILED',
    '47' => 'CURLE_TOO_MANY_REDIRECTS',
    '48' => 'CURLE_UNKNOWN_TELNET_OPTION',
    '49' => 'CURLE_TELNET_OPTION_SYNTAX',
    '51' => 'CURLE_PEER_FAILED_VERIFICATION',
    '52' => 'CURLE_GOT_NOTHING',
    '53' => 'CURLE_SSL_ENGINE_NOTFOUND',
    '54' => 'CURLE_SSL_ENGINE_SETFAILED',
    '55' => 'CURLE_SEND_ERROR',
    '56' => 'CURLE_RECV_ERROR',
    '58' => 'CURLE_SSL_CERTPROBLEM',
    '59' => 'CURLE_SSL_CIPHER',
    '60' => 'CURLE_SSL_CACERT',
    '61' => 'CURLE_BAD_CONTENT_ENCODING',
    '62' => 'CURLE_LDAP_INVALID_URL',
    '63' => 'CURLE_FILESIZE_EXCEEDED',
    '64' => 'CURLE_USE_SSL_FAILED',
    '65' => 'CURLE_SEND_FAIL_REWIND',
    '66' => 'CURLE_SSL_ENGINE_INITFAILED',
    '67' => 'CURLE_LOGIN_DENIED',
    '68' => 'CURLE_TFTP_NOTFOUND',
    '69' => 'CURLE_TFTP_PERM',
    '70' => 'CURLE_REMOTE_DISK_FULL',
    '71' => 'CURLE_TFTP_ILLEGAL',
    '72' => 'CURLE_TFTP_UNKNOWNID',
    '73' => 'CURLE_REMOTE_FILE_EXISTS',
    '74' => 'CURLE_TFTP_NOSUCHUSER',
    '75' => 'CURLE_CONV_FAILED',
    '76' => 'CURLE_CONV_REQD',
    '77' => 'CURLE_SSL_CACERT_BADFILE',
    '78' => 'CURLE_REMOTE_FILE_NOT_FOUND',
    '79' => 'CURLE_SSH',
    '80' => 'CURLE_SSL_SHUTDOWN_FAILED',
    '81' => 'CURLE_AGAIN',
    '82' => 'CURLE_SSL_CRL_BADFILE',
    '83' => 'CURLE_SSL_ISSUER_ERROR',
    '84' => 'CURLE_FTP_PRET_FAILED',
    '85' => 'CURLE_RTSP_CSEQ_ERROR',
    '86' => 'CURLE_RTSP_SESSION_ERROR',
    '87' => 'CURLE_FTP_BAD_FILE_LIST',
    '88' => 'CURLE_CHUNK_FAILED'
];
