services:
  # Maintenance Contract Data Command
  BefineSolutionsAG\Cryptsharesaas\Command\MaintenanceContractDataCommand:
    tags:
      - name: 'console.command'
        command: 'cryptsharesaas:maintenancecontractdata'
        description: 'An example description for a command'
        hidden: false

  # Maintenance Rest Log Command
  BefineSolutionsAG\Cryptsharesaas\Command\MaintenanceRestLogCommand:
    tags:
      - name: 'console.command'
        command: 'cryptsharesaas:maintenancerestlog'
        description: 'An example description for a command'
        hidden: false
