services:
  # Maintenance Contract Data Command
  BefineSolutionsAG\Cryptsharesaas\Command\MaintainanceContractDataCommand:
    tags:
      - name: 'console.command'
        command: 'cryptsharesaas:maintainancecontractdata'
        description: 'An example description for a command'
        hidden: false

  # Maintenance Rest Log Command
  BefineSolutionsAG\Cryptsharesaas\Command\MaintainanceRestLogCommand:
    tags:
      - name: 'console.command'
        command: 'cryptsharesaas:maintainancerestlog'
        description: 'An example description for a command'
        hidden: false
